version: '3.7'

services:
  parallel-processes:
    image: idimsh/mphp7s:latest
    container_name: parallel-processes
    environment:
          PHP_VERSION: 7.3
          DOCROOT: public
          LOG_TO_SRV: 1
    volumes:
      - '.:/srv:rw'

